name: 📨 Deploy Laravel to CyberPanel

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
              set -e
              export NVM_DIR="/opt/nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              nvm use --lts
              cd /home/quiz.amarafif.xyz/public_html
              git stash || true
              git pull origin main
              composer install --no-dev --optimize-autoloader
              php artisan migrate --force
              php artisan optimize:clear
              npm install
              chmod +x node_modules/.bin/vite
              chmod +x node_modules/@esbuild/linux-arm64/bin/esbuild
              npm run build
